- bower.json
- build.sh
- mixpanel-jslib-snippet.js
Add ability to include mixpanel-js from this repository instead of using https://mixpanel.com/help/reference/javascript snippet.
> Add bower.json

- mixpanel.js
- tests/test.js
Adding a $browser_version super property to distinguish individual browser version (eg. Chrome 42 vs. Chrome 40). As discussed in issue #14 this would be useful in determining a site's browser segregation.
I've updated the tests to include the $browser_version property and all tests are passing.
The user agent strings are based on http://www.useragentstring.com/pages/useragentstring.php
> add $browser_version super property

- mixpanel.js
Accurate recognition of Windows Phone and Microsoft Edge.
This JS Library has been tested on my Lumia 526 (Windows Phone 10 + Microsoft Edge), my father's Lumia 630 and my mother's Lumia 1520 (Windows Phone 8.1 + Internet Explorer 11), as well as about 100 users of my app.
> Accurate recognition of Windows Phone and Microsoft Edge

- mixpanel.js
New Opera versions (appears to have changed in version 30) are no longer captured by our current browser picking hierarchy. This PR is intended to add support for the new format and keep support for legacy versions by looking for an additional check on the user agent.
Here is an example new user agent (this looks for the string 'OPR'): "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36 OPR/30.0.1835.125"
> Add support for new Opera browser versions

- mixpanel.js
while $os always matches if Windows Phone, $device had "ipad" as the primary if match - as WP useragents seem to always carry ipad/ipod-like at this point (Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 930) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537) I moved the WP regex block up
@tdumitrescu - thoughts?
> better matching for Windows Phone devices

- mixpanel.js
changing a : to a , to have correct syntax for calls without a json obj
> very minor doc change for people inc

- src/mixpanel-core.js
Recently, Firefox changed the user agent for their mobile browser to the below:
Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) FxiOS/1.3 Mobile/13B143 Safari/601.1.46
Due to this change, our library is mistakenly categorizing this as Mobile Safari. This change will pick up the correct pattern for the user agent and assign the browser property correctly.
> Adding support for Firefox browser on iOS 

- README.md
- mixpanel-jslib-snippet.js
- src/mixpanel-core.js
- tests/test.js
I saw this talked about over in issue #67 and there was a solution given, seems to me as it should be a part of the library as it is a common operation we require.
This PR should address that, if I have missed anything I am happy to fix it up but it appears to be working to me.
> Adding reset method to handle generating a new distinct_id and clearing persistence

- src/mixpanel-core.js
Distinct_id is a optional parameter. If no string is provided, the distinct_id currently in the cookie or local storage will be used.
> Change distinct_id parameter from "required" to "optional" for identify()

- src/utils.js
Added support for recognizing UC Browser.
https://en.wikipedia.org/wiki/UC_Browser
I used their user agent documentation here: http://www.ucweb.com/download/UCBrowser_User_Agent_en.pdf
The UC Browser user agent often includes 'Safari', 'Mobile Safari', so the library currently recognizes UC Browser users as such.
For example:
Mozilla/5.0 (Linux; U; Android 2.3; en-US; MI-ONEPlus) AppleWebKit/534.13 (KHTML, like
Gecko) UCBrowser/8.6.0.199 U3/0.8.0 Mobile Safari/534.13
> Add uc browser

- src/mixpanel-core.js
- src/utils.js
utils.js says in https://github.com/mixpanel/mixpanel-js/blob/v2.12.0/src/utils.js#L4
> since es6 imports are static and we run unit tests from the console, window won't be defined when importing this file
 
but in fact, the bundled js doesn't compile with NodeJS.
This PR fixes the issue by defining browser specific symbols.
NOTE: this PR does not include changes to generated files.
> ensure nodejs compatibility in compile time

- src/mixpanel-core.js
Current implementation that checks whether a super property is already set for register_once does not account for falsy values (false, 0, null). i.e. if the super property is set to 'false' (or any other falsy value), register_once incorrectly overwrites that value
Updated code will check for whether the super property is set
> Update super property check for register_once

- .npmignore
This folder takes up ~50MB in the published package.
I noticed this when trying to deploy to Lambda, where your deployment payload can't be larger than 50MB.
> Ignore examples when publishing to npm

- src/mixpanel-core.js
- src/utils.js
Throw a proper error object, and make sure to catch and log it in the `onreadystatechange` callback so it doesn't propagate to the top level.
Fixes https://github.com/mixpanel/mixpanel-js/issues/169
> Clean up handling of _.JSONDecode errors.

- src/utils.js
- tests/test.js
Fixes https://github.com/mixpanel/mixpanel-js/issues/159
(test cases are piggybacking off an existing set of tests that ultimately exercise the same `getQueryParam()` helper)
> Don't throw exceptions when decoding malformed URL query params

- doc/readme.io/javascript-full-api-reference.md
- src/mixpanel-core.js
- src/utils.js
- tests/test.js
fixes https://github.com/mixpanel/mixpanel-js/issues/184
Several ways to use it:
```js
// for an individual track() call
mixpanel.track('my event', {my: 'props'}, {transport: 'sendBeacon'});
// turn on for every Mixpanel call when page is unloading
// (you would use this to use sendBeacon for everything, including
// mixpanel.people calls)
window.addEventListener(`unload`, function() {
mixpanel.set_config({api_transport: 'sendBeacon'});
mixpanel.track('my event');
mixpanel.people.set({foo: 'bar'});
});
// initialize for all tracking; not recommended as it will prevent any
// request-retry facilities
mixpanel.init('my token', {api_transport: 'sendBeacon'});
mixpanel.track('my event');
```
> add optional navigator.sendBeacon transport

- .travis.yml
6 and 8 are both now past EOL, wooosh
> drop node 6+8 from travis jobs, add 10+12

- src/autotrack.js
- src/mixpanel-core.js
- tests/test.js
Since POST is the default method, GET can be considered an override
that turns off sendBeacon (which is POST-only). Mainly this makes sure
that /decide requests are always GET.
fixes https://github.com/mixpanel/mixpanel-js/issues/244
> sendBeacon vs GET fix

- src/gdpr-utils.js
- src/mixpanel-core.js
- src/mixpanel-persistence.js
- src/utils.js
- tests/test.js
- tests/unit/utils.js
- fixes very short .com/.org domains (e.g., ab.com)
- fixes long TLDs (e.g., foobar.company) (see https://github.com/mixpanel/mixpanel-js/pull/201)
- maintains backwards compatibility with existing integrations by auto-matching >2-part domains with short segments (e.g., www.oxford.ac.uk -> oxford.ac.uk)
- adds `cookie_domain` config option to provide complete control when the out-of-the-box heuristics don't come up with the right domain (the only way to be sure of getting the correct domain is with an extensive up-to-date list like https://publicsuffix.org/)
- adds `cross_site_cookie` config option to use `SameSite=None;Secure` for cases where the cookie domain is considered cross-site (e.g. embedded iframe from a different domain that initializes Mixpanel); fixes …
> cookie options and improvements for cross-subdomain and cross-site cookies

- src/mixpanel-core.js
- tests/test.js
According to [the spec](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1) for requests of type `application/x-www-form-urlencoded`, the body must be escaped. Currently the data is encoded to base64, so it will usually be alphanumeric, but has the chance of producing `+`, `/`, or `=` characters.
It appears the Mixpanel API is already equipped to handle both the escaped and unescaped base64 requests, but proxies or intercepting APIs would need to implement special rules to handle this.
> fix: escape body of POST requests

- src/gdpr-utils.js
- src/mixpanel-core.js
- src/utils.js
It's difficult to debug why events aren't being sent when a user is opted out (particularly in the "Do Not Track" case). This adds some logging for these cases when the library is initialized in debug mode.
> add opt-out logging in debug mode

- src/mixpanel-core.js
Anything below `critical` only shows up if you have DEBUG mode on; not sure why this error was the only one in the function not to get logged as critical.
> snippet double-load error message should always appear, and make it more explicit

- package-lock.json
- package.json
Running `npm install` with npm 8.11+ gives me this diff
```
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
```
> rebuild lockfile with npm 8.11

- src/mixpanel-core.js
- tests/test.js
closes #477.  
Allows setting new configuration `api_extra_query_params`. If this is set, then anything contained is appended to the query string as part of the call to `HTTPBuildQuery` when building the url to make a tracking request to.
> feat: supports passing arbitrary query parameters on send requests

- .github/dependabot.yml
We are ignoring the examples directory. This directory is solely for demonstrating SDK implementation and is neither maintained nor integrated into the application build process.
> Create dependabot yml, ignore findings from examples on future scans
